### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by Vladsop**
Force play-services-location 21.0.1

### CODE REVIEW

**Review by Vladsop — COMMENTED** [review]
Ok

**Comment by christocracy** [comment]
`play-services-location` version is conveniently controlled via the [plugin variable `GOOGLE_API_VERSION`](https://github.com/transistorsoft/cordova-background-geolocation-lt?tab=readme-ov-file#variable-google_api_version-20).  You don't need to hack the `build.gradle`.

```console
$ cordova plugin add cordova-background-geolocation-lt --variable GOOGLE_API_VERSION=21.0.1
```

**Comment by Vladsop** [comment]
> `play-services-location` version is conveniently controlled via the [plugin variable `GOOGLE_API_VERSION`](https://github.com/transistorsoft/cordova-background-geolocation-lt?tab=readme-ov-file#variable-google_api_version-20). You don't need to hack the `build.gradle`.
> 
> ```
> $ cordova plugin add cordova-background-geolocation-lt --variable GOOGLE_API_VERSION=21.0.1
> ```

I do not have control to change the play-services-location version as this plugin is compiled and generated by OutSystems (Low Code Environment Application).  
Facing error is "Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient" and according to [Google Release Notes](https://developers.google.com/android/guides/releases#october_13_2022) the latest changes they did is throwing this error.  One of the fixes is forcing the play-services-location to the latest version, 21.0.1.

**Comment by christocracy** [comment]
I suggest you take that up with outsystems.  I'm not yet prepared to set a minimum `play-services-location` to `21.0.1` as it will upset many others and cause me a surge in support requests.

You can also fork this repo and install the plugin via Git url to your custom fork.

```
$ cordova plugin add <git-url>
```

**Comment by Vladsop** [comment]
> I suggest you take that up with outsystems. I'm not yet prepared to set a minimum `play-services-location` to `21.0.1` as it will upset many others and cause me a surge in support requests.
> 
> You can also fork this repo and install the plugin via Git url to your custom fork.
> 
> ```
> $ cordova plugin add <git-url>
> ```
Pretty Clear, setting it to the minimum 21.0.1 was not intended. It was a mistaken pull request and I cancelled it. I already forked the repo. Thank you

**Pull request closed without merging**
